### ISSUE TITLE
Import CSS with Webpacker

### ISSUE THREAD

**Issue by joaomarceloods** [excid3/simple_discussion#18]
Hi, do you have a suggestion on how to import the default styles using webpacker?

I'm trying to install simple_discussion in a Rails 5.2.3 app that uses webpacker 4 for JS and CSS and doesn't use the asset pipeline. I'm stuck in this step:

> Lastly, add the CSS to your application.css to load some default styles.
>
> *= require simple_discussion

So far, I looked into the following links but none of them provides a good solution:

- https://github.com/rails/webpacker#resolved
- https://github.com/rails/webpacker/issues/488
- https://github.com/rails/webpacker/issues/2023

My bets below didn't work either:

```
# config/webpacker.yml
resolved_paths: ["engine/simple_discussion/app/assets/stylesheets"]

# app/javascript/packs/application.js
import "simple_discussion.scss"

# Webpack error:
Module not found: Error: Can't resolve 'simple_discussion.scss' in '/Users/joao/workspace/learnlifecom/theplatform/backend2/app/javascript/packs'
```

Second try:

```
# config/webpacker.yml
resolved_paths: ["engine/simple_discussion/app/assets/stylesheets"]

# app/javascript/css/application.scss
@import "simple_discussion";

# app/javascript/packs/application.js
import "../css/application.scss";

# Webpack error:
File to import not found or unreadable: simple_discussion.
```

**Comment by excid3** [comment]
Honestly, I wouldn't bother and I would just copy the file from GitHub and drop it in to your Webpacker folder in the app. You can then periodically update the CSS file when you update the gem in the future.

Most of the time you'll want to customize the design anyways, so that'll make it easy to change.

**Comment by joaomarceloods** [comment]
Ok, it makes sense. I thought the styles were complex but now I see it’s a single short file. Thank you.
