### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by perlmunger** [excid3/simple_discussion#20]
Any plans to implement file attachments? I would like to see it where ForumPost has many attachments (file uploads) and then be able to add an initial attachment when the thread is created. I may work on this myself but didn't know if you might already be planning it.

Thanks

**Comment by excid3** [comment]
No plans for that currently. Most public forums you don't want file uploads, so I haven't had any requests for that yet.

If you want to contribute it as an optional feature though, I'd love to see it!

**Comment by perlmunger** [comment]
Ok. Thanks for the quick response. Issues with public uploads that I can think of are:

- Uses too much bandwidth and storage
- Abuses like inappropriate images
- …

What other issues have you found?

Thanks again.

**Comment by excid3** [comment]
That's the main ones I can think of off the top of my head.

**Comment by perlmunger** [comment]
I found a way to add this externally, so thanks again for the feedback.
