### ISSUE TITLE
Additional Common Filters

### ISSUE THREAD

**Issue by perlmunger** [excid3/simple_discussion#21]
I want to add an additional filter called "Hot Topics". I tried adding an additional route to mimic the ones that are already there for `mine`, `participating`, `answered`, and `unaswered`, however, I get a routing issue because the routes that those use must override the ones that use a friendly ID. Is there a way to insert my route 'hot' so that it behaves the same? Just to be clear, I want a route similar to:

> /forum/threads/mine
> /forum/threads/participating
> etc.

Such that

> /forum/threads/hot

would load my action in the controller rather than defaulting to the `show` action.

This is the route I'm using currently:

`get "/forum/threads/hot" => "simple_discussion/forum_threads#hot"`

It tries to load a thread with a friendly ID of "hot" (which doesn't exist, of course) rather than calling my custom action--ostensibly because the resources route for threads by friendly ID are overriding it.

Any suggestions?

Thanks.

**Comment by excid3** [comment]
Prepend your route so it gets matched first. Rails routes run in order, so it will never hit your route if you put it afterwards.

**Comment by excid3** [comment]
Whoops, closed this on accident.

**Comment by perlmunger** [comment]
Derp! For some reason I got it in my head that the last route would override. Ugh. I guess this was a rails question more than simple discussion. Sorry about that. Thanks for your response, though. I appreciate it. Also, it worked!! (in case that wasn't clear) 

Thanks again.

**Comment by excid3** [comment]
I like when issues are this easy. 🤘
