### ISSUE TITLE
Any way to delete a post?

### ISSUE THREAD

**Issue by MirsonCamadro** [excid3/simple_discussion#23]
excuse me, i'm develop a blog and i've used simple discussion, but i,ve had a trouble in the moment when it try to delete a post , i've tried to add dependent::destroy but didn't work;  I'm using rails 6 and i want to know if you can help me, or if you know how can i do that. thanks.

**Comment by excid3** [comment]
You can create your own delete action to do that. There's currently no delete in the code, but it seems like we should probably add it.

**Comment by amanpatel123** [comment]
@MirsonCamadro  I guess you have what you want after #26  was merged. @excid3 can we close this issue?

**Comment by excid3** [comment]
Yessir! 👍
