### ISSUE TITLE
Switch locales in i18n and Mounted Engine

### ISSUE THREAD

**Issue by danielmoralesp** [excid3/simple_discussion#24]
Hi,

I'm having trouble with the `scope "(:locale)"` and `mount SimpleDiscussion::Engine => "/forum"` is giving me this error: ActionController::UrlGenerationError in SimpleDiscussion::ForumThreads#index

And this route not matches: `No route matches {:action=>"index", :controller=>"simple_discussion/forum_threads", :locale=>:es}`

This is part of my routes
```
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|es/ do

    mount SimpleDiscussion::Engine => "/forum"

   ...

end
```

This is the view that gave me the error

```
<% if I18n.locale == :es %>
  <%= link_to t('home.navbar.english'), url_for( locale: :en ), class: "nav-link dropdown-toggle", method: :get %>
<% elsif I18n.locale == :en %>
   <%= link_to t('home.navbar.spanish'), url_for( locale: :es ), class: "nav-link dropdown-toggle", method: :get %>
<% end %>
```

Is there a way to config locales? Thanks!

**Comment by excid3** [comment]
I'd link directly to the simple_discussion_path and pass in the locale.

```erb
<%= link_to "English", simple_discussion_path(locale: :en) %>
<%= link_to "Spanish", simple_discussion_path(locale: :es) %>
```

**Comment by excid3** [comment]
Uploaded a quick example for you: https://github.com/excid3/simple_discussion_locales/blob/master/app/views/layouts/application.html.erb#L16-L20

**Comment by danielmoralesp** [comment]
Hi Chris

Yes, that solved my issue. Thanks. Big fan of your videos here!
