### ISSUE TITLE
Don't know how to build task 'simple_discussion:install:migrations' 

### ISSUE THREAD

**Issue by Johnsalzarulo** [excid3/simple_discussion#25]
Hey There 👋 

I know I must be missing something very obvious here

I am on rails `6.0.1` and I added the gem and ran bundle, no issues. 

However —  When running `rails simple_discussion:install:migrations` 

I get the following error: 
`Don't know how to build task 'simple_discussion:install:migrations' (See the list of available tasks with `rails --tasks`)` 

Anything I can try? 

I know I could manually copy / paste migrations from the source, but I'm wanting to follow the install here. 

Full output: 

```
johnsalzarulo@johns-mbp msapp % rails simple_discussion:install:migrations
The git source `git://github.com/basecrm/basecrm-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config set git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
rails aborted!
Don't know how to build task 'simple_discussion:install:migrations' (See the list of available tasks with `rails --tasks`)
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<top (required)>'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/johnsalzarulo/code/msapp/bin/rails:9:in `<top (required)>'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/johnsalzarulo/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/johnsalzarulo/code/msapp/bin/spring:15:in `require'
/Users/johnsalzarulo/code/msapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
johnsalzarulo@johns-mbp msapp % 
```

**Comment by garysmailes** [comment]
I am having the same issue.

**Comment by excid3** [comment]
Working fine for me in Rails 6.0.3.1.

```bash
$ rails new testapp
$ cd testapp
$ bundle add simple_discussion
$ rails simple_discussion:install:migrations
Copied migration 20200611195027_create_forum_categories.simple_discussion.rb from simple_discussion
Copied migration 20200611195028_create_forum_threads.simple_discussion.rb from simple_discussion
Copied migration 20200611195029_create_forum_posts.simple_discussion.rb from simple_discussion
Copied migration 20200611195030_create_forum_subscriptions.simple_discussion.rb from simple_discussion
```

**Comment by Johnsalzarulo** [comment]
@excid3 — Thanks so much for the fast reply ❤️ Yup just confirmed that it works for me on a fresh Rails app. I'll do that next time on a project like this before opening an issue. 

Let me debug my environment and see what's up. Hopefully my findings will help @garysmailes as well.  

Thanks again

**Comment by excid3** [comment]
👍 

If I had to guess... try a `spring stop` and see if it was (as usual) spring's fault.

**Comment by Johnsalzarulo** [comment]
Just leaving breadcrumbs for @garysmailes or anyone else with similar issues. 

Has **not** worked: 

- ✖️`spring stop` 
- ✖️ Re-running with `bundle exec rails simple_discussion:install:migrations` [based on this similar issue](https://stackoverflow.com/questions/59510916/rails-6-and-action-mailbox-setup)

Based on [this similar issue](https://github.com/rails/rails/issues/33792#issuecomment-421318659) (and others liked it) I tried
- ✖️ Trying adding `require "simple_conversation/engine"` to `config/application`
- ✖️ Trying adding `require "simple_conversation/engine"` to `config/application`

I'll come back to this tomorrow and update my findings

**Comment by excid3** [comment]
Strange, not an issue with Rails 6.0.1 is it?

**Comment by Johnsalzarulo** [comment]
It might be. That’s my next path to explore. ✌️

**Comment by Johnsalzarulo** [comment]
Ok — thanks to the always incredible @ortegacmanuel I was able to figure out the problem. 

- Our codebase specifies `gem "font-awesome-sass", "~> 5.6", ">= 5.6.1"` in the gemfile
- While `simple_discussion` depends on `font-awesome-sass (~> 4.7.0)` 
- This dependency issue leads to bundle installing the `0.1.0` of `simple_discussion` because the 0.1.0 version is the only one that matches all dependency tree of our project.

You'll know you are having an issue like this if your Gemfile.lock specifies `0.1.0`  of `simple_discussion` 

**Solution that worked for me** (Will probably work for @garysmailes as well) 

- Change `gem "font-awesome-sass", "~> 5.6", ">= 5.6.1"` to  `gem "font-awesome-sass", "4.7.0"` 
- Delete your `Gemfile.lock` 
- run `bundle` 
- then the `rails simple_discussion:install:migrations` should be visible. 

### 🎉 
 
<img width="690" alt="Screen Shot 2020-06-13 at 2 55 40 PM" src="https://user-images.githubusercontent.com/3476109/84579808-f58aee80-ad85-11ea-9382-2fe9ef54d40b.png">

**Comment by excid3** [comment]
Thanks @Johnsalzarulo 👍 

That makes a lot of sense. I will relax the font-awesome-sass dependency so that you can install any version >= 4.7. That should fix any future issues with that dependency.

**Comment by excid3** [comment]
Just published 1.0.1 that includes that fix.

**Comment by Johnsalzarulo** [comment]
@excid3 thanks!

**Comment by garysmailes** [comment]
Also works for me. Thanks @Johnsalzarulo
