### ISSUE TITLE
Error while setting development environment

### ISSUE THREAD

**Issue by amanpatel123** [excid3/simple_discussion#27]
While running `rake test` after installing all the dependencies, I get this error, I am not sure if I am doing something wrong here. I will really appreciate if anyone can help

(I am using WSL2)

![image](https://user-images.githubusercontent.com/46072181/89605610-f9923480-d83b-11ea-9dea-f8b29f557abc.png)

**Comment by excid3** [comment]
@amanpatel123 There aren't any tests for this gem right now. You can see that the test folder is basically empty.

The place to start would be to add a dummy app to the test directory. PRs are welcome!
