### ISSUE TITLE
Referencing inexistent model

### ISSUE THREAD

**Issue by okendoken** [excid3/simple_discussion#30]
https://github.com/excid3/simple_discussion/blob/71c897101eb6aead7f750efec8eab2d138f3ed3b/app/models/forum_post.rb#L4

It seems like this line references association that does not exist in the project, thus creating conflicts when running with rails-admin. 

It can be simply removed and everything starts to work well.

I can create a PR.

Thanks for the great gem.

**Comment by excid3** [comment]
Thanks, yes we don't have reactions in the gem, so that would be good to remove. 👍
