### ISSUE TITLE
ArgumentError in SimpleDiscussion::ForumThreads#index

### ISSUE THREAD

**Issue by przbadu** [excid3/simple_discussion#32]
```
Rails: 6.1.3.1
Ruby: 3.0.0p0
simple_discussion: 1.2.0
```

**File:**

- https://github.com/excid3/simple_discussion/blob/master/app/helpers/simple_discussion/forum_threads_helper.rb#L25

**Error:**

![Screenshot_2021-03-30 Action Controller Exception caught](https://user-images.githubusercontent.com/4189129/113083297-f7edf600-91a9-11eb-9625-bb813a629867.png)

**Comment by excid3** [comment]
Should be fixed now. Released as 1.3.0 👍
