### ISSUE TITLE
Trying to create new thread results in this error

### ISSUE THREAD

**Issue by Guo-Ying-Jie** [excid3/simple_discussion#34]
Hey there, I'm probably doing something wrong, but when I try to create a new post using this gem i get these errors

![image](https://user-images.githubusercontent.com/58472470/113589298-18de9d00-9629-11eb-93d3-363a5826cbf7.png)

environment information:

![image](https://user-images.githubusercontent.com/58472470/113589348-272cb900-9629-11eb-9252-d8882c73cc4b.png)

**Comment by excid3** [comment]
Make sure you included the module on your User model as mentioned in the installation steps:

https://github.com/excid3/simple_discussion#installation

**Comment by Guo-Ying-Jie** [comment]
now I'm getting this when I try to open the forum page. I'm really sorry for what must be dumb questions

![image](https://user-images.githubusercontent.com/58472470/113598627-534e3700-9635-11eb-96c6-012b7b27db32.png)

![image](https://user-images.githubusercontent.com/58472470/113598719-7678e680-9635-11eb-98a6-8bcb06984751.png)

**Comment by excid3** [comment]
Make sure you read the instructions:

>Add SimpleDiscussion to your User model. The model must have `name` method which will be used to display the user's name on the forum.

So either add `first_name` and `last_name` columns to your User model or just a `name` column.

**Comment by Guo-Ying-Jie** [comment]
Ok thanks a lot. I need to do a bit more work with devise then. This has been super helpful!
