### ISSUE TITLE
Conflict with Kaminari?

### ISSUE THREAD

**Issue by chrisedington** [excid3/simple_discussion#36]
I use `kaminari (1.2.1)` in my app to handle pagination, and when I install the `simple_discussion` gem, and try navigate to any page of my app I get the following error:

`undefined method 'per' for #<ActiveRecord::AssociationRelation []>`

I saw that the `simple_discussion` gem added `will_paginate` to the `Gemfile.lock` and I assume this is causing the conflict.

Is there any way to get `simple_discussion` working with `Kaminari`?

**Comment by excid3** [comment]
You can use them together if you apply a monkeypatch. Been a long time since I've done that. Something like this: https://github.com/kaminari/kaminari/issues/162#issuecomment-73953413

**Comment by chrisedington** [comment]
Thanks @excid3 - you're a champion.
