### ISSUE TITLE
Routes issue with custom namespace

### ISSUE THREAD

**Issue by chrisedington** [excid3/simple_discussion#37]
I'm trying to use the `simple_discussion` gem within a custom namespace, of `admin`.

My routes are setup as follows:
```
namespace :admin do
      mount SimpleDiscussion::Engine => "/forum"
      .....
```

I seem to be getting an issue which I feel is caused by the non-standard namespace:

```
undefined local variable or method `simple_discussion' for #<#<Class:0x00007f8b03dc71f8>:0x00007f8b03dc4d18>
              
<% if @forum_threads.none? %>

    <div><%= t('search_not_found') %>. <%= t('check_out') %> <%= link_to t('latest_questions'), simple_discussion.forum_threads_path %> <%= t('instead') %> </div>

<% else %>

Application Trace | Framework Trace | Full Trace
simple_discussion (1.3.0) app/views/simple_discussion/forum_threads/index.html.erb:3
```

Any thoughts on how I can get past this one?

**Comment by hartly97** [comment]
Do you want simple discussion to operate only in the admin namespace?

**Comment by chrisedington** [comment]
@hartly97 yeah thats right

**Comment by hartly97** [comment]
So, why only in the admin namespace? Just trying to understand what you're trying to do here.

**Comment by chrisedington** [comment]
@hartly97 I guess that's a good question. I'll try answer that myself first, and perhaps look at putting it in non-namespaced until I have a reason to use a namespace.. I just followed the path of 'where admin related things should go' I guess..

**Comment by hartly97** [comment]
Honestly, it's not necessary to put it in the admin namespace. I've used admin namespaces in my apps  and never placed simple discussion within the admin namespace. Chris has done a great job setting it up for different types of users.

**Comment by chrisedington** [comment]
Thanks @hartly97 appreciate the thought. Closing the issue.
